export const FETCH_STARTED = 'FETCH_STARTED'
export const FETCH_COMPLETE = 'FETCH_COMPLETE'

export const FETCH_AMAZON = 'FETCH_AMAZON'
export const FETCH_EBAY = 'FETCH_EBAY'
export const FETCH_TARGET = 'FETCH_TARGET'
export const MARK_FAVORITE = 'MARK_FAVORITE'
export const UNMARK_FAVORITE = 'UNMARK_FAVORITE'

export const SIGN_IN = 'SIGN_IN'
export const ADD_FAVORITE = 'ADD_FAVORITE'
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE'

